<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <AssemblyName>IconicPvE_Launcher</AssemblyName>
    <RootNamespace>IconicLauncher</RootNamespace>
    <ApplicationIcon>Assets\icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="DiscordRichPresence" Version="1.3.0.28" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\IconicLauncher.Core\IconicLauncher.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets\fallback-config.json" />
    <EmbeddedResource Include="Assets\wow_hero.mp4" Condition="Exists('Assets\wow_hero.mp4')" />
    <Resource Include="Assets\icon.ico" />
    <Resource Include="Assets\dayz_logo.png" />
    <Resource Include="Assets\wow_logo.png" />
    <Resource Include="Assets\wow_hero.png" />
    <None Include="NativeLibs\steam_api64.dll" Link="steam_api64.dll" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
